# Generated by Django 3.1.4 on 2021-01-02 05:07

import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201227_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModule',
            fields=[
                ('ext', models.TextField(blank=True, null=True, validators=[core.validators.validate_json_object_not_empty])),
                ('notes', models.TextField(blank=True, max_length=4000, validators=[django.core.validators.MinLengthValidator(2)])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dashboard_url', models.URLField(blank=True)),
                ('login_url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Daypart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAppModuleMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appmodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appmodule')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('ext', models.TextField(blank=True, null=True, validators=[core.validators.validate_json_object_not_empty])),
                ('notes', models.TextField(blank=True, max_length=4000, validators=[django.core.validators.MinLengthValidator(2)])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('appmodules', models.ManyToManyField(blank=True, through='core.UserAppModuleMapping', to='core.AppModule')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userappmodulemapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
        migrations.CreateModel(
            name='RoleWriteUserMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RoleReadUserMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RoleDataUserMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RoleAdminUserMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='admin',
            field=models.ManyToManyField(blank=True, related_name='role_admin_set', through='core.RoleAdminUserMapping', to='core.UserProfile'),
        ),
        migrations.AddField(
            model_name='role',
            name='data',
            field=models.ManyToManyField(blank=True, related_name='role_data_set', through='core.RoleDataUserMapping', to='core.UserProfile'),
        ),
        migrations.AddField(
            model_name='role',
            name='read',
            field=models.ManyToManyField(blank=True, related_name='role_read_set', through='core.RoleReadUserMapping', to='core.UserProfile'),
        ),
        migrations.AddField(
            model_name='role',
            name='write',
            field=models.ManyToManyField(blank=True, related_name='role_write_set', through='core.RoleWriteUserMapping', to='core.UserProfile'),
        ),
        migrations.AddField(
            model_name='appmodule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='appmodule',
            name='roles',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role'),
        ),
    ]
