# Generated by Django 3.1.4 on 2021-01-10 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Daypart',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='appmodules',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appmodule',
            name='created_by',
        ),
        migrations.AddField(
            model_name='appmodule',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='admin',
            field=models.ManyToManyField(blank=True, related_name='role_admin_set', through='core.RoleAdminUserMapping', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='data',
            field=models.ManyToManyField(blank=True, related_name='role_data_set', through='core.RoleDataUserMapping', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='read',
            field=models.ManyToManyField(blank=True, related_name='role_read_set', through='core.RoleReadUserMapping', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='write',
            field=models.ManyToManyField(blank=True, related_name='role_write_set', through='core.RoleWriteUserMapping', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roleadminusermapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roledatausermapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolereadusermapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolewriteusermapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserAppModuleMapping',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
