# Generated by Django 3.1.4 on 2021-01-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210110_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roledatausermapping',
            name='role',
        ),
        migrations.RemoveField(
            model_name='roledatausermapping',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rolereadusermapping',
            name='role',
        ),
        migrations.RemoveField(
            model_name='rolereadusermapping',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rolewriteusermapping',
            name='role',
        ),
        migrations.RemoveField(
            model_name='rolewriteusermapping',
            name='user',
        ),
        migrations.RemoveField(
            model_name='role',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='role',
            name='data',
        ),
        migrations.RemoveField(
            model_name='role',
            name='read',
        ),
        migrations.RemoveField(
            model_name='role',
            name='write',
        ),
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appmodule',
            name='roles',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.role'),
        ),
        migrations.DeleteModel(
            name='RoleAdminUserMapping',
        ),
        migrations.DeleteModel(
            name='RoleDataUserMapping',
        ),
        migrations.DeleteModel(
            name='RoleReadUserMapping',
        ),
        migrations.DeleteModel(
            name='RoleWriteUserMapping',
        ),
    ]
