# Generated by Django 3.1.4 on 2021-01-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210110_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appmodule',
            old_name='users',
            new_name='user',
        ),
    ]
